default: &default
  adapter: mysql2
  username: root

development:
  <<: *default
  database: dynamic_dns_development

test:
  <<: *default
  database: dynamic_dns_test

production:
  adapter: mysql2
  database: dynamic_dns
  username: "<%= ENV["SQL_USER"] %>"
  password: "<%= ENV["SQL_PASSWORD"] %>"
